version: '2.2'

services:
  eureka:
    image: continuityproject/eureka:1.6.173
    hostname: eureka
    networks:
      - continuity-network
    ports:
      - '8761:8761'
  orchestrator:
    image: continuityproject/orchestrator:1.6.173
    hostname: orchestrator
    networks:
      - continuity-network
    ports:
      - '8089:80'
      - '5009:5000'
    depends_on:
      - rabbitmq-continuity
      - eureka
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --eureka.instance.preferIpAddress=false
      - --eureka.instance.hostName=orchestrator

  rabbitmq-continuity:
    image: rabbitmq:3.6.8-management
    hostname: rabbitmq
    networks:
      continuity-network:
        aliases:
         - rabbitmq
    ports:
      - '15672:15672'
  idpa-application:
    image: continuityproject/idpa-application:1.6.173
    hostname: idpa-application
    networks:
      - continuity-network
    ports:
      - '8085:80'
    depends_on:
      - rabbitmq-continuity
      - eureka
    entrypoint:
      - java
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --eureka.instance.preferIpAddress=false
      - --eureka.instance.hostName=idpa-application
  idpa-annotation:
    image: continuityproject/idpa-annotation:1.6.173
    hostname: idpa-annotation
    networks:
      - continuity-network
    ports:
      - '8081:80'
    depends_on:
      - rabbitmq-continuity
      - eureka
    entrypoint:
      - java
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --eureka.instance.preferIpAddress=false
      - --eureka.instance.hostName=idpa-annotation
  wessbas:
    image: continuityproject/wessbas:1.6.173
    hostname: wessbas
    networks:
      - continuity-network
    ports:
      - '8082:80'
    depends_on:
      - rabbitmq-continuity
      - eureka
    entrypoint:
      - java
      - -jar
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --eureka.instance.preferIpAddress=false
      - --eureka.instance.hostName=wessbas
  request-rates:
    image: continuityproject/request-rates:1.6.173
    hostname: request-rates
    networks:
      - continuity-network
    ports:
      - '8086:80'
    depends_on:
      - rabbitmq-continuity
      - eureka
    entrypoint:
      - java
      - -jar
      - /bin/app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --eureka.instance.preferIpAddress=false
      - --eureka.instance.hostName=request-rates
  jmeter:
    image: continuityproject/jmeter:1.6.173
    hostname: jmeter
    networks:
      - continuity-network
      - shared
    ports:
      - '8083:80'
      - '5003:5000'
    depends_on:
      - rabbitmq-continuity
      - eureka
    cpuset: "14"
    mem_reservation: 2G
    mem_limit: 2G
    entrypoint:
      - java
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - -jar
      - /bin/app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --eureka.instance.preferIpAddress=false
      - --eureka.instance.hostName=jmeter
  session-logs:
    image: continuityproject/session-logs:1.6.173
    hostname: session-logs
    networks:
      - continuity-network
    ports:
      - '8084:80'
      - '5004:5000'
    depends_on:
      - rabbitmq-continuity
      - eureka
    entrypoint:
      - java
      - -jar
      - -Xdebug
      - -Xnoagent
      - -Djava.compiler=NONE
      - -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5000
      - /app.jar
      - --port=80
      - --spring.rabbitmq.host=rabbitmq
      - --eureka.uri=http://eureka:8761/eureka
      - --eureka.instance.preferIpAddress=false
      - --eureka.instance.hostName=session-logs
networks:
  continuity-network:
    external: true
  shared:
    external: true

