version: '2'

services:
  front-end:
    image: continuityproject/sock-shop-front-end:latest
    networks:
      - sock-shop
      - shared
    hostname: front-end
    command: nodemon -L --inspect=0.0.0.0:8888 /usr/src/app/server.js
    environment:
      - ZIPKIN_PORT=8182
      - ZIPKIN_HOST=dl360-1.fsoc.hpi.uni-potsdam.de
    user: root

    restart: always
    cap_drop:
      - all
    read_only: true
    ports:
     - '8888:8888'
    cpuset: "0"
    mem_reservation: 2G
    mem_limit: 2G

  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    networks:
      - sock-shop
      - shared
    ports:
      - '80:80'
      - '8080:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    tmpfs:
      - /var/run:rw,noexec,nosuid
    hostname: edge-router
    restart: always
    cpuset: "1"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
  
  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    networks:
      - sock-shop
      - shared
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    cpuset: "2"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
  
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    networks:
      - sock-shop
      - shared
    environment:
      - ZIPKIN=http://dl360-1.fsoc.hpi.uni-potsdam.de:8182/rest/api/v1/spans
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    cpuset: "3"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
    ports:
     - '9001:80'  
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.5
    networks:
      - sock-shop
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    cpuset: "4"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
  
  carts:
    image: weaveworksdemos/carts:0.4.8
    networks:
      - sock-shop
      - shared
    hostname: carts
    restart: always
    volumes:
      - ./:/agent
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xbootclasspath/p:/agent/inspectit-agent.jar -javaagent:/agent/inspectit-agent.jar -Dinspectit.repository=dl360-1.fsoc.hpi.uni-potsdam.de:9070 -Dinspectit.agent.name=weaveworksdemos-carts -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom 
    cpuset: "5"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
    ports:
     - '9002:80'
  
  carts-db:
    image: mongo:3.4
    networks:
      - sock-shop
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /tmp:rw,noexec,nosuid
    cpuset: "6"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
  
  orders:
    image: continuityproject/sock-shop-orders
    networks:
      - sock-shop
      - shared
    hostname: orders
    restart: always
    volumes:
      - ./:/agent
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
     - JAVA_OPTS=-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=2500 -Xbootclasspath/p:/agent/inspectit-agent.jar -javaagent:/agent/inspectit-agent.jar -Dinspectit.repository=dl360-1.fsoc.hpi.uni-potsdam.de:9070 -Dinspectit.agent.name=weaveworksdemos-orders -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -Djava.security.egd=file:/dev/urandom
    ports:
      - '2500:2500'
    cpuset: "7"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
    ports:
     - '9003:80'

  
  orders-db:
    image: mongo:3.4
    networks:
      - sock-shop
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /tmp:rw,noexec,nosuid
    cpuset: "8"
    mem_reservation: 2G
    mem_limit: 2G
    user: root

  
  shipping:
    image: weaveworksdemos/shipping:0.4.8
    networks:
      - sock-shop
      - shared
    hostname: shipping
    restart: always
    volumes:
      - ./:/agent
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xbootclasspath/p:/agent/inspectit-agent.jar -javaagent:/agent/inspectit-agent.jar -Dinspectit.repository=dl360-1.fsoc.hpi.uni-potsdam.de:9070 -Dinspectit.agent.name=weaveworksdemos-shipping -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    cpuset: "9"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
    ports:
     - '9004:80'

  rabbitmq:
    image: rabbitmq:3.6.8
    networks:
      - sock-shop
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    cpuset: "10"
    mem_reservation: 2G
    mem_limit: 2G
    user: root

  payment:
    image: weaveworksdemos/payment:0.4.3
    networks:
      - sock-shop
      - shared
    environment:
      - ZIPKIN=http://dl360-1.fsoc.hpi.uni-potsdam.de:8182/rest/api/v1/spans
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    cpuset: "11"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
    ports:
     - '9005:80'

  user:
    image: weaveworksdemos/user:0.4.6
    networks:
      - sock-shop
      - shared
    environment:
      - ZIPKIN=http://dl360-1.fsoc.hpi.uni-potsdam.de:8182/rest/api/v1/spans
      - MONGO_HOST=user-db:27017

    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    cpuset: "12"
    mem_reservation: 2G
    mem_limit: 2G
    user: root


  user-db:
    image: weaveworksdemos/user-db:0.4.6
    networks:
      - sock-shop
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    tmpfs:
      - /tmp:rw,noexec,nosuid
    cpuset: "13"
    mem_reservation: 2G
    mem_limit: 2G
    user: root
    ports:
     - '9006:80'


networks:
  sock-shop:
    external: true
  shared:
    external: true
