version: '3'

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
        expose:
          - 9090
        ports:
          - 9090:9090

    zipkin:
      image: openzipkin/zipkin
      ports:
        - 9411:9411

    open-xtrace:
      image: continuityproject/zipkin-to-open-xtrace-converter:0.0.1
      ports:
        - 8345:8345